name: apkainzynierka
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0-alpha

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  provider: ^6.0.4
  logger: ^1.1.0
  flutter_picker: ^2.0.5
  freezed_annotation: ^2.2.0
  bottom_navy_bar: ^6.0.0
  dotted_border: ^2.0.0+3
  hive: ^2.2.3
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0
  kiwi: ^4.0.3
  syncfusion_flutter_charts: ^20.3.59
  mockito: ^5.3.2
  event_bus: ^2.0.0
  go_router: ^6.0.1
  intl: ^0.17.0
  numberpicker: ^2.1.1
  google_fonts: ^3.0.1
  table_calendar: ^3.0.8
  path_provider: ^2.0.11
  printing: ^5.9.0
  pdf: ^3.8.4
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  flutter_native_timezone: ^2.0.0
  workmanager: ^0.5.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  kiwi_generator: ^4.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
    - family: BalooDa2
      fonts:
        - asset: fonts/BalooDa2-Bold.ttf
          weight: 700
        - asset: fonts/BalooDa2-Regular.ttf
  assets:
    - assets/ic_launcher.png
