name: apkainzynierka
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  provider: ^6.0.4
  logger: ^1.1.0
  flutter_picker: ^2.0.5
  freezed_annotation: ^2.2.0
  bottom_navy_bar: ^6.0.0
  dotted_border: ^2.0.0+3
  hive: ^2.2.3
  json_annotation: ^4.7.0
  hive_flutter: ^1.1.0
  kiwi: ^4.0.3
  syncfusion_flutter_charts: ^20.3.59
  mockito: ^5.3.2
  event_bus: ^2.0.0
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  kiwi_generator: ^4.0.3

flutter:
  uses-material-design: true
